services:
  postgres:
    image: postgres:14.12-alpine
    environment:
      - POSTGRES_USER=gaia
      - POSTGRES_PASSWORD=gaia123
      - POSTGRES_DB=gaia
      - PGTZ=Asia/Jakarta
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432
