services:
  postgres:
    image: postgres:13.7
    environment:
      - POSTGRES_USER=gaia
      - POSTGRES_PASSWORD=gaia123
      - POSTGRES_DB=gaia
      - PGTZ=Asia/Jakarta
      - TZ=Asia/Jakarta
    ports:
      - 5432:5432

  pubsub:
    image: thekevjames/gcloud-pubsub-emulator:latest
    platform: linux/amd64
    environment:
      - PUBSUB_PROJECT1=gaia-dev,gaia-dev-topic:gaia-dev-topic-sub
    ports:
      - 8681:8681
      - 8682:8682
