// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	msg "github.com/kgmedia-data/gaia/pkg/msg"
	mock "github.com/stretchr/testify/mock"
)

// IBatchProcessor is an autogenerated mock type for the IBatchProcessor type
type IBatchProcessor[T interface{}] struct {
	mock.Mock
}

// ExecuteBatch provides a mock function with given fields: messages
func (_m *IBatchProcessor[T]) ExecuteBatch(messages []msg.Message[T]) error {
	ret := _m.Called(messages)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]msg.Message[T]) error); ok {
		r0 = rf(messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIBatchProcessor creates a new instance of IBatchProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBatchProcessor[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *IBatchProcessor[T] {
	mock := &IBatchProcessor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
